# Assignment No. 13

Name:Rushabh Ratnaparkhi

College:Your College Name

Branch:Computer Engineering

Domain:AIML

GitHub Repository:

In [2]:
#Q1
import numpy as np
array_1D = np.array([10, 20, 30, 40, 50])

array_2D = np.array([[1, 2, 3], 
                     [4, 5, 6],
                     [7, 8, 9]])

print("1D Array:")
print(array_1D)
print("Data type:", array_1D.dtype)
print("Shape:", array_1D.shape)

print("\n2D Array:")
print(array_2D)
print("Data type:", array_2D.dtype)
print("Shape:", array_2D.shape)

1D Array:
[10 20 30 40 50]
Data type: int64
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type: int64
Shape: (3, 3)


In [1]:
#Q2
import numpy as np

array1 = np.zeros(8)

array2= np.ones((4,4))

array3 = np.zeros((3,3))

print("1D array of zeros:")
print(array1)

print("\n2D array of oens:")
print(array2)

print("\n3D array of zeros:")
print(array3)


1D array of zeros:
[0. 0. 0. 0. 0. 0. 0. 0.]

2D array of oens:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3D array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Q3
import numpy as np
